# Google Analytics Tracking ID
google_analytics:

# Default portfolio post
default_cover_image: images/unsplash.jpg
default_post_title: Portfolio Item

# GitHub Discussions comments
giscus:
  enable: true
  repo: xiaoyu233kao/xiaoyu233kao.github.io
  repo_id: R_kgDOTZO2Gw
  category: Announcements
  category_id: DIC_kwDOTZO2G84DBSiW
  mapping: pathname
